### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by JuliaArtes** [JuliaArtes/1_2_-wallpaper-_calculator#1]
@Coursar проверить ДЗ

**Comment by coursar** [comment]
Не вижу кода:

https://github.com/JuliaArtes/1_2_-wallpaper-_calculator/blob/2cb28363bbc16dfa60be1f945a906b21940acafe/src/Main.java#L1-L3

**Comment by JuliaArtes** [comment]
@coursar 
посмотрите еще раз пожалуйста

**Comment by coursar** [comment]
Пофиксить #3

**Comment by JuliaArtes** [comment]
убрала комментарии

**Comment by JuliaArtes** [comment]
@coursar 
все issues закрыты, но отметки о сдаче дз нет. Остались еще замечания?
